# Generated by Django 5.0.3 on 2024-03-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SessionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_name", models.CharField(max_length=20, unique=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("max_no_player", models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30, unique=True)),
                ("steamID", models.CharField(max_length=17, unique=True)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("password_hash256", models.CharField(max_length=64, unique=True)),
                ("rating", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="SessionList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lfgAPI.sessiondata",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lfgAPI.userdata",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sessiondata",
            name="host_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="host",
                to="lfgAPI.userdata",
            ),
        ),
        migrations.AddField(
            model_name="sessiondata",
            name="participants",
            field=models.ManyToManyField(
                through="lfgAPI.SessionList", to="lfgAPI.userdata"
            ),
        ),
    ]
